- name: install nginx
  ansible.builtin.dnf:
   name: nginx
   state: latest

- name: start and enable nginx
  ansible.builtin.service:
   name: nginx
   state: started
   enabled: yes

- name: task from common
  ansible.builtin.import_role:
   name: common
   tasks_from: app-pre-req


- name: copy backend conf
  ansible.builtin.template:
   src: expense.conf
   dest: /etc/nginx/default.d/expense.conf
  notify:
   - restart nginx