- name: install mysql
  ansible.builtin.dnf:
   name: mysql
   state: installed

- name: start and enable mysql service
  ansible.builtin.service:
   name: mysql
   state: started
   enable: true

- name: Get MySQL version with non-default credentials
  community.mysql.mysql_info:
   login_user: "{{ login_user }}"
   login_password: "{{ login_password }}"
   login_host: "{{ login_host }}"
   filter: version
  ignore_errors: true
  register: mysql_info

- name: Get MySQL version
  ansible.builtin.debug:
   msg: "output is {{ mysql_info }}"