- name: Install MySQL Client & MySQL Python Module
  ansible.builtin.dnf:
   name:
    - mysql
    - python3-PyMySQL
   state: present

- name: Start mysql service
  ansible.builtin.service:
   name: mysqld
   state: started
   enabled: yes


- name: Get MySQL version with non-default credentials
  community.mysql.mysql_info:
   login_user: "{{ login_user }}"
   login_password: "{{ login_password }}"
   login_host: "{{ login_host }}"
   filter: version
  ignore_errors: true
  register: mysql_info

- name: Get MySQL version
  ansible.builtin.debug:
   msg: "output is {{ mysql_info }}"