- name: Install mysql-server
  ansible.builtin.dnf:
    name: mysql-server
    state: present

- name: Enable and start mysql-server
  ansible.builtin.systemd_service:
    name: mysqld
    enabled: true
    state: restarted

- name: Setup MySQL root password
  ansible.builtin.command:
    cmd: mysql_secure_installation --set-root-pass {{ db_pass }}