- name: Remove application directory
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: absent

- name: Create application directory
  ansible.builtin.file:
    path: "{{ app_path }}"
    state: directory

- name: Download and extract application
  ansible.builtin.unarchive:
    src: "https://expense-artifacts.s3.amazonaws.com/expense-{{ component }}-v2.zip"
    dest: "{{ app_path }}"
    remote_src: true