- name: delete old files
  ansible.builtin.file:
   path: "{{ app_path }}"
   state: absent
  ignore_errors: true

 
- name: create app directory
  ansible.builtin.file:
   path: "{{ app_path }}"
   state: directory

- name: unzip backend code
  ansible.builtin.unarchive:
   src:  "https://expense-builds.s3.us-east-1.amazonaws.com/expense-{{ component }}-v2.zip"
   dest: "{{ app_path }}"
   remote_src: yes